`timescale 1ns / 1ps

// Lab 9 drop-in replacement for the Lab 8 image FIFO.
//
// Lab 9 specifies an asynchronous FIFO while hardware still uses one 100 MHz
// system clock. This wrapper therefore connects the same system clock to both
// asynchronous FIFO domains. The FIFO controller still uses independent
// Gray-coded pointers and two-flop pointer synchronizers, so the architecture
// remains valid if the domains become truly asynchronous in a later lab.
//
// Producer/write side: RGB ROM reader
// Consumer/read side: sequencer
module seq_tx_img_fifo #(
    parameter int unsigned FIFO_WIDTH = 24,
    parameter int unsigned FIFO_DEPTH = 32
) (
    // Write domain: RGB ROM + Sequencer
    input logic wr_clk,
    input logic wr_rst_n,

    // Read domain: Message Composer + UART TX
    input logic rd_clk,
    input logic rd_rst_n,

    // push_req must be generated by the RGB ROM / image-fetch side.
    // pop_req must be generated by the sequencer side.
    input  logic                           push_req,
    input  logic                           pop_req,

    // RGB pixel input: {R, G, B}
    input  logic [FIFO_WIDTH-1:0]          data_in,

    // Threshold levels:
    // ae_level: occupancy at/below which the FIFO is almost empty.
    // af_level: free entries at/below which the FIFO is almost full.
    input  logic [$clog2(FIFO_DEPTH+1)-1:0] ae_level,
    input  logic [$clog2(FIFO_DEPTH+1)-1:0] af_level,

    // FIFO output. data_out updates on the clock edge of an accepted pop_req.
    output logic [FIFO_WIDTH-1:0]          data_out,

    // Status.
    // fifo_level is a write-domain occupancy estimate.
    output logic [$clog2(FIFO_DEPTH+1)-1:0] fifo_level,
    output logic                           empty,
    output logic                           almost_empty,
    output logic                           half_full,
    output logic                           almost_full,
    output logic                           full,
    output logic                           error,

    // Back-pressure for the RGB ROM reader. It is hysteretic:
    // 1 at almost_full, released only after draining to ae_level.
    output logic                           rom_pause
);

    logic                            wr_en;
    logic                            rd_en;
    logic [$clog2(FIFO_DEPTH)-1:0]   wr_addr;
    logic [$clog2(FIFO_DEPTH)-1:0]   rd_addr;

    fifo_controller #(
        .FIFO_DEPTH(FIFO_DEPTH)
    ) u_fifo_controller (

        .wr_clk        (wr_clk),
        .wr_rst_n      (wr_rst_n),
        .push_req      (push_req),

        .rd_clk        (rd_clk),
        .rd_rst_n      (rd_rst_n),
        .pop_req       (pop_req),

        .ae_level      (ae_level),
        .af_level      (af_level),

        .wr_en         (wr_en),
        .rd_en         (rd_en),
        .wr_addr       (wr_addr),
        .rd_addr       (rd_addr),

        .fifo_level    (fifo_level),
        .empty         (empty),
        .almost_empty  (almost_empty),
        .half_full     (half_full),
        .almost_full   (almost_full),
        .full          (full),
        .rom_pause     (rom_pause),
        .error         (error)
    );

    ram_1r1w #(
        .RAM_WIDTH(FIFO_WIDTH),
        .RAM_DEPTH(FIFO_DEPTH)
    ) u_ram_1r1w (

        .wr_clk   (wr_clk),
        .wr_en    (wr_en),
        .wr_addr  (wr_addr),
        .data_in  (data_in),

        .rd_clk   (rd_clk),
        .rd_rst_n (rd_rst_n),
        .rd_en    (rd_en),
        .rd_addr  (rd_addr),
        .data_out (data_out)
    );

endmodule
