`timescale 1ns / 1ps

module sequencer #(
    parameter int IMG_WIDTH   = 256,
    parameter int IMG_HEIGHT  = 256,
    parameter int ROM_DEPTH   = 16384,
    parameter int ROM_ADDR_W  = 14
)(
    input  logic clk,
    input  logic rst_n,
    input  logic start,

    // Write-domain FIFO backpressure.
    // Generated by FIFO controller with hysteresis.
    input logic rom_pause,

    // ROM inputs
    input  logic [31:0] rom_r_data,
    input  logic [31:0] rom_g_data,
    input  logic [31:0] rom_b_data,

    // FIFO interface
    output logic        fifo_wr_en,
    output logic [23:0] fifo_data,

    // ROM address
    output logic [ROM_ADDR_W-1:0] rom_addr,

    // Status / monitor
    output logic [9:0] row_cnt,
    output logic [9:0] col_cnt,
    output logic       transfer_done,
    output logic       busy,
    output logic       rts
);

    typedef enum logic [3:0] {
        IDLE,
        WAIT_START,
        READ_ROM,
        PUSH_FIFO,
        CHECK_FIFO,
        WAIT_FIFO_RESUME,
        DONE
    } state_t;

    state_t state, next_state;

    logic [1:0]  pixel_idx;  // 0..3 inside each ROM word
    logic [31:0] rom_r_q;
    logic [31:0] rom_g_q;
    logic [31:0] rom_b_q;

    logic [7:0]  r_pixel;
    logic [7:0]  g_pixel;
    logic [7:0]  b_pixel;

    logic last_col;
    logic last_row;
    logic last_pixel;

    // =========================================================
    // STATUS SIGNALS
    // =========================================================
    assign busy = (state != IDLE);

    // Temporary implementation.
    // Verify active level during full-system integration.
    assign rts = busy;

    assign last_col   = (col_cnt == IMG_WIDTH  - 1);
    assign last_row   = (row_cnt == IMG_HEIGHT - 1);
    assign last_pixel = last_col && last_row;

    // =========================================================
    // FSM - STATE REGISTER
    // =========================================================
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            state <= IDLE;
        else
            state <= next_state;
    end

    // =========================================================
    // FSM - NEXT STATE LOGIC
    // =========================================================
    always_comb begin
        next_state = state;

        case (state)

            IDLE: begin
                if (start)
                    next_state = WAIT_START;
            end

            // Allows ROM address 0 to settle before capture.
            WAIT_START: begin
                next_state = READ_ROM;
            end

            // Capture one 32-bit word from each ROM.
            READ_ROM: begin
                next_state = PUSH_FIFO;
            end

            // Push four RGB pixels from the captured ROM words.
            PUSH_FIFO: begin
                // Final pixel of the entire image
                if (last_pixel)
                    next_state = DONE;

                // Finished all four pixels of the current ROM word
                else if (pixel_idx == 2'd3)
                    next_state = CHECK_FIFO;

                // Continue unpacking the same ROM word
                else
                    next_state = PUSH_FIFO;
            end

            // Decide whether another ROM word may be read.
            CHECK_FIFO: begin
                if (rom_pause)
                    next_state = WAIT_FIFO_RESUME;
                else
                    next_state = READ_ROM;
            end

            // Backpressure hysteresis:
            // resume only after the FIFO drains sufficiently.
            WAIT_FIFO_RESUME: begin
                if (!rom_pause)
                    next_state = READ_ROM;
                else
                    next_state = WAIT_FIFO_RESUME;
            end

            DONE: begin
                next_state = IDLE;
            end

            default: begin
                next_state = IDLE;
            end

        endcase
    end

    // =========================================================
    // PIXEL INDEX
    // =========================================================
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            pixel_idx <= 2'd0;

        else if (state == READ_ROM)
            pixel_idx <= 2'd0;

        else if (state == PUSH_FIFO)
            pixel_idx <= pixel_idx + 2'd1;
    end

    // =========================================================
    // CAPTURE ROM DATA
    // =========================================================
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rom_r_q <= 32'd0;
            rom_g_q <= 32'd0;
            rom_b_q <= 32'd0;
        end

        else if (state == READ_ROM) begin
            rom_r_q <= rom_r_data;
            rom_g_q <= rom_g_data;
            rom_b_q <= rom_b_data;
        end
    end

    // =========================================================
    // ROM SLICING
    // Each ROM word contains four 8-bit channel values.
    // =========================================================
    assign r_pixel = rom_r_q[31 - 8 * pixel_idx -: 8];
    assign g_pixel = rom_g_q[31 - 8 * pixel_idx -: 8];
    assign b_pixel = rom_b_q[31 - 8 * pixel_idx -: 8];

    // =========================================================
    // FIFO OUTPUTS
    // =========================================================
    assign fifo_data = {r_pixel, g_pixel, b_pixel};

    always_comb begin
        fifo_wr_en = 1'b0;

        if (state == PUSH_FIFO)
            fifo_wr_en = 1'b1;
    end

    // =========================================================
    // ROW / COLUMN COUNTERS
    // Advance only when a pixel is actually pushed into the FIFO.
    // =========================================================
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            row_cnt <= 10'd0;
            col_cnt <= 10'd0;
        end

        else if (state == IDLE && start) begin
            row_cnt <= 10'd0;
            col_cnt <= 10'd0;
        end

        else if (state == PUSH_FIFO) begin
            if (last_col) begin
                col_cnt <= 10'd0;

                if (!last_row)
                    row_cnt <= row_cnt + 10'd1;
            end

            else begin
                col_cnt <= col_cnt + 10'd1;
            end
        end
    end

    // =========================================================
    // ROM ADDRESS COUNTER
    // Advance after all four pixels of a ROM word were pushed.
    // =========================================================
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            rom_addr <= '0;

        else if (state == IDLE && start)
            rom_addr <= '0;

        else if (
            state == PUSH_FIFO &&
            pixel_idx == 2'd3 &&
            !last_pixel
        )
            rom_addr <= rom_addr + 1'b1;
    end

    // =========================================================
    // TRANSFER DONE
    // =========================================================
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            transfer_done <= 1'b0;

        else if (state == IDLE && start)
            transfer_done <= 1'b0;

        else if (state == PUSH_FIFO && last_pixel)
            transfer_done <= 1'b1;
    end

endmodule
